version: '3.1'
services:
  ts-rabbitmq:
    container_name: container-ts-rabbitmq
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=tsservice
      - RABBITMQ_DEFAULT_PASS=tsservice
  ts-redis:
    container_name: container-ts-redis
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

